# Generated by Django 3.1.2 on 2020-10-30 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BairBudalite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budali',
            name='image_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
