# Generated by Django 3.1.2 on 2020-11-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BairBudalite', '0003_auto_20201030_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klipove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='pohodi',
            old_name='description',
            new_name='description_small',
        ),
    ]
