# Generated by Django 3.1.2 on 2020-11-04 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BairBudalite', '0004_auto_20201104_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('pohod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BairBudalite.pohodi')),
            ],
        ),
    ]
