# Generated by Django 3.1.2 on 2020-11-04 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BairBudalite', '0005_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('pohod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BairBudalite.pohodi')),
            ],
        ),
    ]
