# Generated by Django 3.1.2 on 2020-11-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BairBudalite', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pohodi',
            old_name='description_small',
            new_name='description',
        ),
    ]
