# Generated by Django 3.1.2 on 2020-12-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BairBudalite', '0007_auto_20201111_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budali',
            name='image_src',
            field=models.CharField(max_length=500),
        ),
    ]
