# Generated by Django 3.1.2 on 2020-12-03 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budalite_authentication', '0003_auto_20201202_2030'),
        ('BairBudalite', '0008_auto_20201202_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_profile',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='budalite_authentication.userprofile'),
            preserve_default=False,
        ),
    ]
