# Generated by Django 3.1.2 on 2020-12-11 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BairBudalite', '0011_auto_20201203_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='images',
            name='pohod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BairBudalite.pohodi'),
        ),
        migrations.AddField(
            model_name='images',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BairBudalite.project'),
        ),
    ]
