# Generated by Django 3.1.2 on 2020-12-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BairBudalite', '0012_auto_20201211_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
