# Generated by Django 3.1.2 on 2020-12-11 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BairBudalite', '0013_auto_20201211_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='pohod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BairBudalite.pohodi'),
        ),
        migrations.AlterField(
            model_name='images',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BairBudalite.project'),
        ),
    ]
