# Generated by Django 3.1.2 on 2020-12-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BairBudalite', '0016_auto_20201211_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='first_image',
            field=models.CharField(max_length=255),
        ),
    ]
